apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq-helm.fullname" . }}
  labels:
    {{- include "rabbitmq-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: go
      protocol: TCP
      name: go-app
  selector:
    {{- include "rabbitmq-helm.selectorLabels" . | nindent 4 }}
